# AmirhosseinZare
## DL-SM
## video: 02:30 untill 04:15

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])

B = np.array([[2,9,0,3,0],
              [3,6,8,-2,2],
              [1,3,5,0,1],
              [3,0,2,0,5]])

print(A.shape)
print(B.shape)

print("matmul C:")
print(np.matmul(A,B))

print("einsum C:")
print(np.einsum("ij,jk -> ik", A, B))

(3, 4)
(4, 5)
matmul C:
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]
einsum C:
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [ ]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])

B = np.array([[2,9,0,3],
              [3,6,8,-2],
              [1,3,5,0]])

print(A.shape)
print(B.shape)

print("hardmond C:")
print(A*B)

print("einsum C:")
print(np.einsum("ij,ij -> ij", A, B))

(3, 4)
(3, 4)
hardmond C:
[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]
einsum C:
[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [ ]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])


print("Transposed A :")
print(A.T)

print("einsum Transposed A:")
print(np.einsum("ij -> ji", A))

Transposed A :
[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]
einsum Transposed A:
[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [ ]:
A = np.array([[[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]],

              [[1,3,1,22],
               [0,2,2,0],
               [1,5,4,1]]])

B = np.array([[[2,9,0,3,0],
              [3,6,8,-2,2],
              [1,3,5,0,1],
              [3,0,2,0,5]],

              [[1,0,0,3,0],
               [3,0,4,-2,2],
               [1,0,2,0,0],
               [3,0,1,1,0]]])

print(A.shape)
print(B.shape)

print("batch Mul C:")
print(np.matmul(A,B))

print("einsum C:")
print(np.einsum("bij,bjk -> bik", A, B))

(2, 3, 4)
(2, 4, 5)
batch Mul C:
[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]
einsum C:
[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [ ]:
A = np.array([[[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]],

              [[1,3,1,22],
               [0,2,2,0],
               [1,5,4,1]]])

print("sum A:")
print(np.sum(A))

print("einsum A:")
print(np.einsum('bij -> ', A))

sum A:
72
einsum A:
72


In [ ]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0]])

print("Axis 0 sum A:")
print(np.sum(A, axis=0))

print("einsum A:")
print(np.einsum('ij -> j', A))

print("Axis 0 sum A:")
print(np.sum(A, axis=1))

print("einsum A:")
print(np.einsum('ij -> i', A))

Axis 0 sum A:
[ 5  9 11  5]
einsum A:
[ 5  9 11  5]
Axis 0 sum A:
[15  5 10]
einsum A:
[15  5 10]


In [ ]:
Q = np.random.randn(32,64, 512)
K = np.random.randn(32,128, 512)

In [ ]:
np.einsum("bqm,bkm -> bqk", Q,K).shape

(32, 64, 128)

In [ ]:
A = np.random.randn(2,4,4,2)
B = np.random.randn(2,4,4,1)

In [ ]:
np.einsum("bcik,bcij -> bckj", B, A).shape

(2, 4, 1, 2)

In [ ]:
np.matmul(np.transpose(B, (0,1,3,2)), A).shape

(2, 4, 1, 2)

In [ ]:
import tensorflow as tf
tensor_three_d = tf.constant([
    [[1,2,3],
    [4,5,6]],

    [[7,8,9],
    [-1,-2,-3]],

    [[2,5,9],
    [-2,6,-3]],
])
print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d, axis=0).shape)

(3, 2, 3)
(1, 3, 2, 3)


In [ ]:
x = tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded = tf.expand_dims(x,axis=0)
print(x_expanded)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [ ]:
x_squeezed = tf.squeeze(x_expanded, axis=0)
for i in range(2):
  x_squeezed = tf.squeeze(x_squeezed, axis=0)

print(x_squeezed)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,3],
    [4,5,6]],

    [[7,8,9],
    [-1,-2,-3]],

    [[2,5,9],
    [-2,6,-3]],
])
print(tensor_three_d.shape)
x_exp = tf.expand_dims(tensor_three_d, axis=3)
print(tf.squeeze(x_exp, axis=3))
print(tf.reshape(x_exp, [3,2,3]))

(3, 2, 3)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [-1 -2 -3]]

 [[ 2  5  9]
  [-2  6 -3]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [-1 -2 -3]]

 [[ 2  5  9]
  [-2  6 -3]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
x_reshape = tf.constant([[3,5,6,6],
                         [4,6,-1,2]])
tf.reshape(x_reshape, [-1])
tf.reshape(x_reshape, [8])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  5,  6,  6,  4,  6, -1,  2], dtype=int32)>

In [ ]:
t1 = [[[1,2,3],
       [4,5,6]]]

t2 = [[[7,8,9],
      [10,11,12]]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1, t2], axis=2)

(1, 2, 3)
(1, 2, 3)


<tf.Tensor: shape=(1, 2, 6), dtype=int32, numpy=
array([[[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]], dtype=int32)>

In [ ]:
tf.stack([t1,t2,t1], axis=0)

<tf.Tensor: shape=(3, 1, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]]]], dtype=int32)>

In [ ]:
tf.concat([tf.expand_dims(t, axis=0) for t in [t1,t2]], axis=0)

<tf.Tensor: shape=(2, 1, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)>

In [ ]:
t = tf.constant([[1,2,3],
                [4,5,6]])
paddings = tf.constant([[1,5],
                        [2,2]])
tf.pad(t, paddings, "CONSTANT", constant_values = 0)

<tf.Tensor: shape=(8, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
params = tf.constant(['p0','p1','p2','p3','p4','p5'])
print(params.shape)
params[1:3+1]

(6,)


<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [ ]:
tf.gather(params, [0,3,5])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p3', b'p5'], dtype=object)>

In [ ]:
params = tf.constant([
                      [[0.0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]],

                      [[0.0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]]
                      ])
print(params.shape)
tf.gather(params, [1, 0], axis=0)

(2, 4, 3)


<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [10., 11., 12.],
        [20., 21., 22.],
        [30., 31., 32.]],

       [[ 0.,  1.,  2.],
        [10., 11., 12.],
        [20., 21., 22.],
        [30., 31., 32.]]], dtype=float32)>

In [ ]:
indices = [[0],
           [1]]

params = [['a', 'b'],
          ['c', 'd']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'a', b'b'],
       [b'c', b'd']], dtype=object)>

In [ ]:
indices = [2,1]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(), dtype=string, numpy=b'f'>

In [ ]:
indices = [[0,1],
           [1,0]]

params = [[['a0', 'b0'],
          ['c0', 'd0']],

          [['a1', 'b1'],
          ['c1', 'd1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c0', b'd0'],
       [b'a1', b'b1']], dtype=object)>

In [ ]:
indices = [[[0,1],
           [1,0]],

           [[0,0],
           [1,1]]]

params = [[['a0', 'b0'],
          ['c0', 'd0']],

          [['a1', 'b1'],
          ['c1', 'd1']]]

tf.gather_nd(params, indices, batch_dims = 0)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>

In [ ]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [-1,-2,-3]
])
print(tensor_two_d.shape)

(4, 3)


In [ ]:
tensor_two_d = [
    [1,2,3],
    [4,],
    [7,8,9,12,16],
    [-1,-3]
]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 3], [4], [7, 8, 9, 12, 16], [-1, -3]]>


In [ ]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3,1,4,1,5,9,2,6],
    row_lengths=[4,0,3,1,0]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]], values=[11,56], dense_shape=[5,6]
)

In [ ]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [ ]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [ ]:
tensor_string = tf.constant(["hello", "i am", "a string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [ ]:
tf.strings.join(tensor_string, separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello+i am+a string'>

In [ ]:
x = tf.constant([1,2])

In [ ]:
x_var = tf.Variable(x, name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [ ]:
x_var.assign_add([3,6])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 8], dtype=int32)>

In [ ]:
with tf.device('CPU:0'):
  x_1 = tf.constant([1,3,4])
  x_2 = tf.constant([1])

with tf.device('GPU:0'):
  x_3 = x_1 + x_2


print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:GPU:0
