# AmirhosseinZare
## chapter 4

In [1]:
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import Normalizer

In [2]:
# Create feature
feature = np . array ([[ - 500.5 ],
                       [ - 100.1 ],
                       [ 0 ],
                       [ 100.1 ],
                       [ 900.9 ]])


# Create scaler
minmax_scale = preprocessing . MinMaxScaler ( feature_range= ( 0 , 1 ))
# Scale feature
scaled_feature = minmax_scale . fit_transform ( feature )

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [3]:
minmax_scale = preprocessing . MinMaxScaler ( feature_range= ( -1 , 1 ))
# Scale feature
scaled_feature = minmax_scale . fit_transform ( feature )

scaled_feature

array([[-1.        ],
       [-0.42857143],
       [-0.28571429],
       [-0.14285714],
       [ 1.        ]])

In [4]:
x = np . array ([[ - 1000.1 ],
                 [ - 200.2 ],
                 [ 500.5 ],
                 [ 600.6 ],
                 [ 9000.9 ]])
# Create scaler
scaler = preprocessing . StandardScaler ()
# Transform the feature
standardized = scaler . fit_transform ( x )
# Show feature
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [5]:
# Print mean and standard deviation
print ( "Mean:" , round ( standardized . mean ()))
print ( "Standard deviation:" , standardized . std ())

Mean: 0
Standard deviation: 1.0


In [6]:
robust_scaler = preprocessing . RobustScaler ()
# Transform feature
robust_scaler . fit_transform (x)

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

In [7]:
features = np . array ([[ 0.5 , 0.5 ],
                        [ 1.1 , 3.4 ],
                        [ 1.5 , 20.2 ],
                        [ 1.63 , 34.4 ],
                        [ 10.9 , 3.3 ]])
# Create normalizer
normalizer = Normalizer ( norm= "l2" )
# Transform feature matrix
normalizer . transform ( features )

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [8]:
features = np . array ([[ 3 , 4 ],
                        [ 1 , 2 ],
                        [ 6 , 6 ]])
# Create normalizer
normalizer = Normalizer ( norm= "l1" )
# Transform feature matrix
normalizer . transform ( features )

array([[0.42857143, 0.57142857],
       [0.33333333, 0.66666667],
       [0.5       , 0.5       ]])

In [9]:
features = np . array ([[ 0.5 , 0.5 ],
                        [ 1.1 , 3.4 ],
                        [ 1.5 , 20.2 ],
                        [ 1.63 , 34.4 ],
                        [ 10.9 , 3.3 ]])
# Create normalizer
normalizer = Normalizer ( norm= "l2" )
# Transform feature matrix
normalizer . transform ( features )

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [10]:
# Transform feature matrix
features_l1_norm = Normalizer ( norm= "l1" ) . transform ( features )
# Show feature matrix
features_l1_norm

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [11]:
# Print sum
print ( "Sum of the first observation \' s values:" ,
features_l1_norm [ 0 , 0 ] + features_l1_norm [ 0 , 1 ])

Sum of the first observation ' s values: 1.0


In [12]:
from sklearn.preprocessing import PolynomialFeatures

In [13]:
features = np . array ([[ 2 , 3 ],
                        [ 2 , 3 ],
                        [ 2 , 3 ]])
# Create PolynomialFeatures object
polynomial_interaction = PolynomialFeatures ( degree=2 , include_bias=False )
# Create polynomial features
polynomial_interaction . fit_transform ( features )

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

In [14]:
features = np . array ([[ 2 , 3 ],
                        [ 2 , 3 ],
                        [ 2 , 3 ]])
# Create PolynomialFeatures object
polynomial_interaction = PolynomialFeatures ( degree=3 , include_bias=False )
# Create polynomial features
polynomial_interaction . fit_transform ( features )

array([[ 2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.],
       [ 2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.],
       [ 2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.]])

In [15]:
features = np . array ([[ 2 , 3 ],
                        [ 2 , 3 ],
                        [ 2 , 3 ]])
# Create PolynomialFeatures object
polynomial_interaction = PolynomialFeatures ( degree=4 , include_bias=False )
# Create polynomial features
polynomial_interaction . fit_transform ( features )

array([[ 2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27., 16., 24., 36., 54.,
        81.],
       [ 2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27., 16., 24., 36., 54.,
        81.],
       [ 2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27., 16., 24., 36., 54.,
        81.]])

In [16]:
interaction = PolynomialFeatures ( degree=2 ,
interaction_only=True , include_bias=False )
interaction . fit_transform ( features )

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

In [17]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

In [18]:
# Create feature matrix
features = np . array ([[ 2 , 3 ],
                        [ 2 , 3 ],
                        [ 2 , 3 ]])
# Define a simple function
def add_ten ( x : int ) -> int :
  return x + 10
# Create transformer
ten_transformer = FunctionTransformer ( add_ten )
# Transform feature matrix
ten_transformer . transform ( features )

array([[12, 13],
       [12, 13],
       [12, 13]])

In [19]:
import numpy as np
# Define a simple function
def my_ln ( x : int ) -> int :
  return np.log(x)
# Create transformer
ten_transformer = FunctionTransformer ( my_ln )
# Transform feature matrix
ten_transformer . transform ( features )

array([[0.69314718, 1.09861229],
       [0.69314718, 1.09861229],
       [0.69314718, 1.09861229]])

In [20]:
ten_transformer . transform ( features[:,0] )

array([0.69314718, 0.69314718, 0.69314718])

In [21]:
import pandas as pd
# Create DataFrame
df = pd . DataFrame ( features , columns= [ "feature_1" , "feature_2" ])
# Apply function
df . apply ( add_ten )

feature_1  feature_2
0         12         13
1         12         13
2         12         13

In [22]:
import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

In [23]:
# Create simulated data
features , _ = make_blobs ( n_samples = 10 ,
                            n_features = 2 ,
                            centers = 1 ,
                            random_state = 1 )
# Replace the first observation's values with extreme values
features

array([[-1.83198811,  3.52863145],
       [-2.76017908,  5.55121358],
       [-1.61734616,  4.98930508],
       [-0.52579046,  3.3065986 ],
       [ 0.08525186,  3.64528297],
       [-0.79415228,  2.10495117],
       [-1.34052081,  4.15711949],
       [-1.98197711,  4.02243551],
       [-2.18773166,  3.33352125],
       [-0.19745197,  2.34634916]])

In [24]:
features [ 0 , 0 ] = 10000
features [ 0 , 1 ] = 10000

In [25]:
features

array([[ 1.00000000e+04,  1.00000000e+04],
       [-2.76017908e+00,  5.55121358e+00],
       [-1.61734616e+00,  4.98930508e+00],
       [-5.25790464e-01,  3.30659860e+00],
       [ 8.52518583e-02,  3.64528297e+00],
       [-7.94152277e-01,  2.10495117e+00],
       [-1.34052081e+00,  4.15711949e+00],
       [-1.98197711e+00,  4.02243551e+00],
       [-2.18773166e+00,  3.33352125e+00],
       [-1.97451969e-01,  2.34634916e+00]])

In [26]:
# Create detector
outlier_detector = EllipticEnvelope ( contamination= .001 )
# Fit detector
outlier_detector . fit ( features )
# Predict outliers
outlier_detector . predict ( features )

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [27]:
# Create one feature
feature = features [:, 0 ]
# Create a function to return index of outliers
def indicies_of_outliers ( x : int ) -> np . array ( int ):
  q1 , q3 = np . percentile ( x , [ 25 , 75 ])
  iqr = q3 - q1
  lower_bound = q1 - ( iqr * 1.5 )
  upper_bound = q3 + ( iqr * 1.5 )
  return np . where (( x > upper_bound ) | ( x < lower_bound ))
# Run function
indicies_of_outliers ( feature )

(array([0]),)

In [28]:
import pandas as pd
# Create DataFrame
houses = pd . DataFrame ()
houses [ 'Price' ] = [ 534433 , 392333 , 293222 , 4322032 ]
houses [ 'Bathrooms' ] = [ 2 , 3.5 , 2 , 116 ]
houses [ 'Square_Feet' ] = [ 1500 , 2500 , 1500 , 48000 ]
# Filter observations
houses [ houses [ 'Bathrooms' ] < 20 ]

Price  Bathrooms  Square_Feet
0  534433        2.0         1500
1  392333        3.5         2500
2  293222        2.0         1500

In [29]:
# Create feature based on boolean condition
houses [ "Outlier" ] = np . where ( houses [ "Bathrooms" ] < 20 , 0 , 1 )
# Show data
houses

Price  Bathrooms  Square_Feet  Outlier
0   534433        2.0         1500        0
1   392333        3.5         2500        0
2   293222        2.0         1500        0
3  4322032      116.0        48000        1

In [30]:
# Log feature
houses [ "Log_Of_Square_Feet" ] = [ np . log ( x ) for x in houses [ "Square_Feet" ]]
# Show data
houses

Price  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956